server:
  port: 9001
topic:
    product: product
    category: category
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
configuration:
  engineName: solr
  collectionName: product
  url: http://localhost:8983/solr/